import React, { useEffect, useMemo, useState } from 'react';
import { Pencil, Plus, RefreshCw, ShieldOff, Trash2, UserCheck, UsersRound, X } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import { companyMembersService } from '../../multiTenant/companyMembersService';
import { listCompanyMembers, type CompanyMemberListItem } from '../../multiTenant/companyMembersReadService';
import { companyMemberErrorMessage, validPhone } from '../../multiTenant/companyMemberUi';
import { hasPermission } from '../../multiTenant/permissions';

type Dialog = 'create' | 'edit' | 'disable' | 'reactivate' | 'delete' | 'reset' | null;
const fieldClass = 'w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 dark:border-slate-700 dark:bg-slate-950';

function DialogShell({ title, busy, close, children }: { title: string; busy: boolean; close: () => void; children: React.ReactNode }) {
  return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-slate-950/60 p-4" onMouseDown={() => !busy && close()}><section role="dialog" aria-modal="true" dir="rtl" className="max-h-[92vh] w-full max-w-lg overflow-y-auto rounded-2xl bg-white p-5 shadow-2xl dark:bg-slate-900" onMouseDown={event => event.stopPropagation()}><div className="mb-5 flex justify-between"><h2 className="text-lg font-black">{title}</h2><button type="button" disabled={busy} onClick={close}><X /></button></div>{children}</section></div>;
}

export function CompanyMembersModule() {
  const { authSession } = useAuth();
  const companyId = authSession?.userType === 'company' ? authSession.companyId : undefined;
  const canManage = Boolean(authSession?.role && hasPermission(authSession.role, 'company:members:write'));
  const [members, setMembers] = useState<CompanyMemberListItem[]>([]); const [loading, setLoading] = useState(true);
  const [dialog, setDialog] = useState<Dialog>(null); const [selected, setSelected] = useState<CompanyMemberListItem | null>(null);
  const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [search, setSearch] = useState('');
  const [form, setForm] = useState({ name: '', email: '', temporaryPassword: '', phone: '', jobTitle: '', status: 'active' });
  const load = async () => { if (!companyId) return; setLoading(true); try { setMembers((await listCompanyMembers(companyId)).filter(member => member.role === 'company_super_admin' || member.role === 'manager')); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [companyId]);
  const close = () => { if (saving) return; setDialog(null); setSelected(null); setError(''); };
  const open = (next: Dialog, member?: CompanyMemberListItem) => { setSelected(member || null); setError(''); setNotice(''); setForm(member ? { name: member.name, email: member.email || '', temporaryPassword: '', phone: member.phone || '', jobTitle: member.jobTitle || '', status: member.status } : { name: '', email: '', temporaryPassword: '', phone: '', jobTitle: '', status: 'active' }); setDialog(next); };
  const execute = async (operation: () => Promise<{ success: boolean; code: string; message: string }>, message: string) => { setSaving(true); setError(''); try { const result = await operation(); if (!result.success) { setError(companyMemberErrorMessage(result.code)); return; } setNotice(message); setDialog(null); setSelected(null); await load(); } catch (failure) { setError(failure instanceof Error ? failure.message : 'تعذر تنفيذ العملية.'); } finally { setSaving(false); } };
  const create = async (event: React.FormEvent) => { event.preventDefault(); if (!form.name.trim() || !/^\S+@\S+\.\S+$/.test(form.email) || form.temporaryPassword.length < 12 || !validPhone(form.phone)) { setError('تحقق من الاسم والبريد والهاتف، وكلمة مرور مؤقتة من 12 حرفًا على الأقل.'); return; } await execute(() => companyMembersService.create({ name: form.name.trim(), email: form.email.trim().toLowerCase(), temporaryPassword: form.temporaryPassword, phone: form.phone.trim() || undefined, jobTitle: form.jobTitle.trim() || undefined, role: 'manager' }), 'تم إنشاء المدير بنجاح.'); };
  const update = async (event: React.FormEvent) => { event.preventDefault(); if (!selected || !form.name.trim() || !validPhone(form.phone)) return setError('تحقق من الاسم ورقم الهاتف.'); await execute(() => companyMembersService.update({ uid: selected.uid, name: form.name.trim(), phone: form.phone.trim() || undefined, jobTitle: form.jobTitle.trim() || undefined }), 'تم تحديث المدير.'); };
  const visible = useMemo(() => members.filter(member => `${member.name} ${member.email || ''} ${member.jobTitle || ''}`.toLowerCase().includes(search.toLowerCase())), [members, search]);
  const protectedOwner = selected?.role === 'company_super_admin'; const self = selected?.uid === authSession?.uid;
  if (!canManage) return <div className="p-10 text-center">غير مصرح لك بإدارة المديرين.</div>;
  return <section dir="rtl" className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-black">إدارة المديرين</h1><p className="text-sm text-slate-500">صاحب الشركة والمديرون فقط. العمال تتم إدارتهم من قسم العمال.</p></div><button onClick={() => open('create')} className="flex items-center gap-2 rounded-xl bg-amber-500 px-4 py-2.5 font-black text-slate-950"><Plus size={17}/>إضافة مدير</button></div>{notice && <p className="rounded-xl bg-emerald-100 p-3 text-emerald-800">{notice}</p>}<input className={fieldClass} placeholder="بحث بالاسم أو البريد أو المسمى الوظيفي" value={search} onChange={event => setSearch(event.target.value)} />{loading ? <p className="p-8 text-center">جارٍ التحميل…</p> : <div className="overflow-x-auto rounded-2xl border"><table className="w-full min-w-[760px] text-right text-sm"><thead className="bg-slate-100 dark:bg-slate-800"><tr>{['الاسم','البريد','المسمى','الدور','الحالة','الإجراءات'].map(label => <th key={label} className="p-3">{label}</th>)}</tr></thead><tbody>{visible.map(member => <tr key={member.uid} className="border-t"><td className="p-3 font-bold">{member.name}</td><td className="p-3" dir="ltr">{member.email}</td><td className="p-3">{member.jobTitle || '—'}</td><td className="p-3">{member.role === 'company_super_admin' ? 'صاحب الشركة' : 'مدير'}</td><td className="p-3">{member.status === 'active' ? 'نشط' : 'معطل'}</td><td className="p-3"><div className="flex flex-wrap gap-2"><button onClick={() => open('edit', member)} disabled={member.role === 'company_super_admin'} className="text-amber-600 disabled:opacity-30"><Pencil size={16}/></button>{member.status === 'active' ? <button onClick={() => open('disable', member)} disabled={member.role === 'company_super_admin' || member.uid === authSession?.uid} className="text-rose-600 disabled:opacity-30"><ShieldOff size={16}/></button> : <button onClick={() => open('reactivate', member)} disabled={member.role === 'company_super_admin'} className="text-emerald-600 disabled:opacity-30"><UserCheck size={16}/></button>}<button onClick={() => open('reset', member)} disabled={member.role === 'company_super_admin'} className="disabled:opacity-30"><RefreshCw size={16}/></button><button onClick={() => open('delete', member)} disabled={member.role === 'company_super_admin' || member.uid === authSession?.uid} className="text-rose-700 disabled:opacity-30"><Trash2 size={16}/></button></div></td></tr>)}</tbody></table>{visible.length === 0 && <div className="p-8 text-center text-slate-500"><UsersRound className="mx-auto mb-2"/>لا يوجد مديرون مطابقون.</div>}</div>}
  {dialog === 'create' && <DialogShell title="إضافة مدير" busy={saving} close={close}><form onSubmit={create} className="space-y-3"><input className={fieldClass} placeholder="الاسم" value={form.name} onChange={e => setForm({...form,name:e.target.value})}/><input type="email" className={fieldClass} placeholder="البريد الإلكتروني" value={form.email} onChange={e => setForm({...form,email:e.target.value})}/><input type="password" className={fieldClass} placeholder="كلمة المرور المؤقتة" value={form.temporaryPassword} onChange={e => setForm({...form,temporaryPassword:e.target.value})}/><input className={fieldClass} placeholder="رقم الهاتف" value={form.phone} onChange={e => setForm({...form,phone:e.target.value})}/><input className={fieldClass} placeholder="المسمى الوظيفي" value={form.jobTitle} onChange={e => setForm({...form,jobTitle:e.target.value})}/><select className={fieldClass} value="active" disabled><option value="active">نشط</option></select>{error && <p className="text-rose-600">{error}</p>}<button disabled={saving} className="rounded-xl bg-amber-500 px-4 py-2 font-black">إنشاء المدير</button></form></DialogShell>}
  {dialog === 'edit' && selected && !protectedOwner && <DialogShell title="تعديل المدير" busy={saving} close={close}><form onSubmit={update} className="space-y-3"><input className={fieldClass} value={form.name} onChange={e => setForm({...form,name:e.target.value})}/><input className={fieldClass} value={form.email} readOnly disabled/><input className={fieldClass} placeholder="رقم الهاتف" value={form.phone} onChange={e => setForm({...form,phone:e.target.value})}/><input className={fieldClass} placeholder="المسمى الوظيفي" value={form.jobTitle} onChange={e => setForm({...form,jobTitle:e.target.value})}/><p className="text-xs text-slate-500">البريد والشركة والدور غير قابلة للتعديل.</p>{error && <p className="text-rose-600">{error}</p>}<button disabled={saving} className="rounded-xl bg-amber-500 px-4 py-2 font-black">حفظ</button></form></DialogShell>}
  {dialog && selected && ['disable','reactivate','delete','reset'].includes(dialog) && !protectedOwner && <DialogShell title="تأكيد العملية" busy={saving} close={close}><p className="mb-4">تأكيد تنفيذ العملية على المدير: <b>{selected.name}</b></p>{error && <p className="mb-3 text-rose-600">{error}</p>}<button disabled={saving || self} onClick={() => void execute(() => dialog === 'disable' ? companyMembersService.disable({uid:selected.uid}) : dialog === 'reactivate' ? companyMembersService.reactivate({uid:selected.uid}) : dialog === 'delete' ? companyMembersService.delete({uid:selected.uid}) : companyMembersService.sendPasswordReset({uid:selected.uid}), dialog === 'delete' ? 'تم حذف المدير.' : 'تم تنفيذ العملية بنجاح.')} className="rounded-xl bg-rose-600 px-4 py-2 font-black text-white">تأكيد</button></DialogShell>}
  </section>;
}
