import React from 'react';
import { Calendar, CheckCircle2, Circle, ClipboardPenLine, Edit, Trash2, UserRound } from 'lucide-react';
import { WorkTask } from '../../types';

interface WorkTasksPanelProps { tasks: WorkTask[]; isWorker: boolean; onEdit: (task: WorkTask) => void; onDelete: (task: WorkTask) => void; onToggle: (task: WorkTask) => void; }

export const WorkTasksPanel: React.FC<WorkTasksPanelProps> = ({ tasks, isWorker, onEdit, onDelete, onToggle }) => {
  const ordered = [...tasks].sort((a, b) => a.executionDate.localeCompare(b.executionDate));
  return <section className="overflow-hidden rounded-2xl border border-indigo-200 bg-white shadow-sm dark:border-indigo-900/50 dark:bg-slate-900">
    <div className="flex items-center justify-between border-b border-indigo-100 bg-indigo-50/70 px-5 py-4 dark:border-indigo-900/50 dark:bg-indigo-950/20"><h3 className="flex items-center gap-2 text-sm font-black text-indigo-900 dark:text-indigo-200"><ClipboardPenLine className="h-4 w-4" />{isWorker ? 'أعمالي المكلّف بها' : 'أعمال مستقلة عن الأوردرات'}</h3><span className="rounded-full bg-white px-2 py-0.5 text-[10px] font-black text-indigo-700 dark:bg-slate-800 dark:text-indigo-300">{ordered.length}</span></div>
    {ordered.length === 0 ? <p className="p-6 text-center text-sm font-medium text-slate-400">{isWorker ? 'لا توجد أعمال مسندة إليك حاليًا.' : 'لا توجد أعمال إضافية حتى الآن.'}</p> : <div className="divide-y divide-slate-100 dark:divide-slate-800">{ordered.map((task) => <div key={task.id} className="flex items-start gap-3 p-4 hover:bg-slate-50/80 dark:hover:bg-slate-800/40"><button type="button" onClick={() => onToggle(task)} className="mt-0.5 shrink-0 text-emerald-600 hover:text-emerald-700" title={task.status === 'completed' ? 'إعادة فتح العمل' : 'تحديد كمكتمل'}>{task.status === 'completed' ? <CheckCircle2 className="h-5 w-5" /> : <Circle className="h-5 w-5" />}</button><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h4 className={`font-black ${task.status === 'completed' ? 'text-slate-400 line-through' : 'text-slate-900 dark:text-white'}`}>{task.title}</h4><span className={`rounded-full px-2 py-0.5 text-[10px] font-bold ${task.status === 'completed' ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-950/50 dark:text-emerald-300' : 'bg-amber-100 text-amber-700 dark:bg-amber-950/50 dark:text-amber-300'}`}>{task.status === 'completed' ? 'مكتمل' : 'قيد التنفيذ'}</span></div>{task.details && <p className="mt-1 whitespace-pre-line text-xs leading-relaxed text-slate-500 dark:text-slate-400">{task.details}</p>}<div className="mt-2 flex flex-wrap items-center gap-3 text-[11px] font-semibold text-slate-500"><span className="flex items-center gap-1"><Calendar className="h-3.5 w-3.5 text-emerald-500" />{task.executionDate}</span>{!isWorker && <span className="flex items-center gap-1"><UserRound className="h-3.5 w-3.5 text-amber-500" />{task.workerName}</span>}</div></div>{!isWorker && <div className="flex shrink-0 gap-1"><button type="button" onClick={() => onEdit(task)} className="rounded-lg p-1.5 text-slate-400 hover:bg-indigo-50 hover:text-indigo-600 dark:hover:bg-indigo-950/30" title="تعديل"><Edit className="h-4 w-4" /></button><button type="button" onClick={() => onDelete(task)} className="rounded-lg p-1.5 text-slate-400 hover:bg-rose-50 hover:text-rose-600 dark:hover:bg-rose-950/30" title="حذف"><Trash2 className="h-4 w-4" /></button></div>}</div>)}</div>}
  </section>;
};
