import * as crypto from 'node:crypto';
import * as admin from 'firebase-admin';

export type CompanyMemberError = 'OK' | 'UNAUTHORIZED' | 'FORBIDDEN' | 'INVALID_INPUT' | 'COMPANY_NOT_FOUND' | 'COMPANY_INACTIVE' | 'MEMBER_NOT_FOUND' | 'MEMBER_DISABLED' | 'EMAIL_EXISTS' | 'USERNAME_EXISTS' | 'MAX_USERS_REACHED' | 'ROLE_NOT_ALLOWED' | 'SELF_ROLE_CHANGE_FORBIDDEN' | 'SELF_DISABLE_FORBIDDEN' | 'CANNOT_MANAGE_COMPANY_ADMIN' | 'LAST_COMPANY_ADMIN' | 'AUTH_CREATION_FAILED' | 'MEMBER_CREATION_FAILED' | 'WORKER_CREATION_FAILED' | 'AUDIT_LOG_FAILED' | 'RESET_NOT_SUPPORTED' | 'ROLLBACK_FAILED' | 'UNKNOWN_ERROR';
export type ManagedRole = 'manager' | 'employee' | 'worker';
export type CompanyRole = ManagedRole | 'company_super_admin';
export type CompanyMemberResponse<T = Record<string, never>> = { success: boolean; code: CompanyMemberError; message: string; data?: T };
export interface CreateCompanyMemberRequest { name: string; role: ManagedRole; email?: string; username?: string; loginCode?: string; phone?: string; companyId?: string; }
export interface UpdateCompanyMemberRequest { uid: string; name?: string; phone?: string; displaySettings?: Record<string, boolean | string | number>; companyId?: string; }
export interface ChangeCompanyMemberRoleRequest { uid: string; role: ManagedRole; companyId?: string; }
export interface DisableCompanyMemberRequest { uid: string; companyId?: string; }
export interface ReactivateCompanyMemberRequest { uid: string; companyId?: string; }
export interface SendCompanyMemberPasswordResetRequest { uid: string; companyId?: string; }
export interface ResetWorkerLoginCodeRequest { workerId: string; loginCode: string; companyId?: string; }
export type CreateCompanyMemberResponse = CompanyMemberResponse<{ uid: string; workerId?: string } | Record<string, never>>;
export type UpdateCompanyMemberResponse = CompanyMemberResponse;
export type ChangeCompanyMemberRoleResponse = CompanyMemberResponse;
export type DisableCompanyMemberResponse = CompanyMemberResponse;
export type ReactivateCompanyMemberResponse = CompanyMemberResponse;
export type SendCompanyMemberPasswordResetResponse = CompanyMemberResponse<{ testResetLink?: string }>;
export type ResetWorkerLoginCodeResponse = CompanyMemberResponse;

type AuthContext = { uid: string } | undefined;
type MemberDoc = { uid: string; companyId?: string; name?: string; email?: string; role?: CompanyRole; status?: string; workerId?: string; phone?: string };
type Deps = { db: FirebaseFirestore.Firestore; auth: admin.auth.Auth; emulator?: boolean };
const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const workerName = /^[a-z0-9_-]{2,80}$/i;
const ok = <T = Record<string, never>>(message: string, data?: T): CompanyMemberResponse<T> => data === undefined ? { success: true, code: 'OK', message } : { success: true, code: 'OK', message, data };
const fail = (code: CompanyMemberError, message: string): CompanyMemberResponse => ({ success: false, code, message });
const normalize = (v: unknown) => typeof v === 'string' ? v.trim() : '';
const hasMemberWritePermission = (role: CompanyRole) => role === 'company_super_admin'; // Mirrors the current Permission Matrix; managers do not have company:members:write.
export const hashWorkerLoginCode = (loginCode: string): string => { const salt = crypto.randomBytes(16); const N = 16384, r = 8, p = 1; const value = crypto.scryptSync(loginCode, salt, 64, { N, r, p, maxmem: 128 * 1024 * 1024 }); return `scrypt$${N}$${r}$${p}$${salt.toString('base64')}$${value.toString('base64')}`; };
export const canManageCompanyMember = (actorRole: CompanyRole, targetRole: CompanyRole, _action: 'create' | 'update' | 'role' | 'disable'): boolean => actorRole === 'company_super_admin' && targetRole !== 'company_super_admin';

export class CompanyMemberService {
  constructor(private readonly deps: Deps) {}

  private async caller(auth: AuthContext): Promise<{ company: FirebaseFirestore.DocumentSnapshot; member: FirebaseFirestore.QueryDocumentSnapshot } | CompanyMemberResponse> {
    if (!auth?.uid) return fail('UNAUTHORIZED', 'يجب تسجيل الدخول أولاً.');
    const matches = await this.deps.db.collectionGroup('members').where('uid', '==', auth.uid).get();
    const active = matches.docs.filter(doc => doc.data().status === 'active');
    if (active.length !== 1) return fail('UNAUTHORIZED', 'عضوية الشركة غير صالحة أو غير مفعلة.');
    const member = active[0]; const companyRef = member.ref.parent.parent;
    if (!companyRef) return fail('UNAUTHORIZED', 'عضوية الشركة غير صالحة.');
    const company = await companyRef.get();
    if (!company.exists) return fail('COMPANY_NOT_FOUND', 'الشركة غير موجودة.');
    if (!['active', 'trial'].includes(String(company.data()?.status))) return fail('COMPANY_INACTIVE', 'حالة الشركة لا تسمح بإدارة الأعضاء.');
    return { company, member };
  }
  private async authorize(auth: AuthContext): Promise<{ company: FirebaseFirestore.DocumentSnapshot; member: FirebaseFirestore.QueryDocumentSnapshot } | CompanyMemberResponse> {
    const context = await this.caller(auth);
    if ('success' in context) return context;
    if (!hasMemberWritePermission(context.member.data().role as CompanyRole)) return fail('FORBIDDEN', 'ليس لديك صلاحية إدارة أعضاء الشركة.');
    return context;
  }
  private async rateLimit(companyId: string, actor: string, action: string): Promise<CompanyMemberResponse | null> {
    const ref = this.deps.db.doc(`companyMemberRateLimits/${crypto.createHash('sha256').update(`${companyId}\0${actor}\0${action}`).digest('hex')}`);
    const allowed = await this.deps.db.runTransaction(async tx => { const snapshot = await tx.get(ref); const data = snapshot.data() || {}; const now = Date.now(); const windowStartedAt = typeof data.windowStartedAt === 'number' ? data.windowStartedAt : now; const inWindow = now - windowStartedAt < 60_000; const count = inWindow ? Number(data.count || 0) : 0; if (count >= 10) return false; tx.set(ref, { count: count + 1, windowStartedAt: inWindow ? windowStartedAt : now, updatedAt: admin.firestore.FieldValue.serverTimestamp() }, { merge: true }); return true; });
    return allowed ? null : fail('FORBIDDEN', 'تم تجاوز الحد المؤقت لهذه العملية. حاول لاحقاً.');
  }
  private async audit(companyId: string, action: string, performedBy: string, targetUid: string, targetRole?: string, metadata: Record<string, unknown> = {}): Promise<void> {
    await this.deps.db.collection(`companies/${companyId}/auditLogs`).add({ action, companyId, targetUid, targetRole: targetRole || null, performedBy, metadata, success: true, timestamp: admin.firestore.FieldValue.serverTimestamp() });
  }
  private validCode(code: string) { return code.length >= 6 && code.length <= 128 && /[0-9]/.test(code); }

  async create(input: unknown, auth: AuthContext): Promise<CreateCompanyMemberResponse> {
    const context = await this.authorize(auth); if ('success' in context) return context;
    const rate = await this.rateLimit(context.company.id, auth!.uid, 'create'); if (rate) return rate;
    const data = (input || {}) as CreateCompanyMemberRequest; const name = normalize(data.name); const role = data.role;
    if (!name || !['manager', 'employee', 'worker'].includes(role)) return fail('INVALID_INPUT', 'بيانات العضو أو دوره غير صحيحة.');
    const isWorker = role === 'worker'; const email = normalize(data.email).toLowerCase(); const username = normalize(data.username).toLowerCase(); const loginCode = typeof data.loginCode === 'string' ? data.loginCode : '';
    if ((!isWorker && (!emailPattern.test(email) || username || loginCode)) || (isWorker && (!workerName.test(username) || !this.validCode(loginCode) || email))) return fail('INVALID_INPUT', 'بيانات إنشاء العضو غير صحيحة.');
    const companyRef = context.company.ref; const maxUsers = Number(context.company.data()?.maxUsers);
    if (!Number.isInteger(maxUsers) || maxUsers < 1) return fail('INVALID_INPUT', 'إعداد maxUsers للشركة غير صالح.');
    if (!isWorker) { try { if (await this.deps.auth.getUserByEmail(email)) return fail('EMAIL_EXISTS', 'البريد الإلكتروني مستخدم بالفعل.'); } catch (e) { if ((e as { code?: string }).code !== 'auth/user-not-found') return fail('AUTH_CREATION_FAILED', 'تعذر التحقق من البريد الإلكتروني.'); } }
    let uid: string | undefined; let workerRef: FirebaseFirestore.DocumentReference | undefined; let workerSecretRef: FirebaseFirestore.DocumentReference | undefined; let memberRef: FirebaseFirestore.DocumentReference | undefined;
    try {
      if (isWorker) { const matches = await companyRef.collection('workers').where('username', '==', username).limit(1).get(); if (!matches.empty) return fail('USERNAME_EXISTS', 'اسم المستخدم مستخدم داخل هذه الشركة.'); workerRef = companyRef.collection('workers').doc(); workerSecretRef = companyRef.collection('workerSecrets').doc(workerRef.id); uid = `worker_${companyRef.id}_${workerRef.id}`; try { await this.deps.auth.createUser({ uid, displayName: name }); } catch { return fail('AUTH_CREATION_FAILED', 'تعذر إنشاء حساب العامل.'); } }
      else { try { uid = (await this.deps.auth.createUser({ displayName: name, email, emailVerified: false })).uid; } catch (e) { return (e as { code?: string }).code === 'auth/email-already-exists' ? fail('EMAIL_EXISTS', 'البريد الإلكتروني مستخدم بالفعل.') : fail('AUTH_CREATION_FAILED', 'تعذر إنشاء حساب المستخدم.'); } }
      memberRef = companyRef.collection('members').doc(uid);
      await this.deps.db.runTransaction(async tx => { const company = await tx.get(companyRef); const current = Number(company.data()?.memberCount || 0); if (!company.exists) throw new MemberFailure('COMPANY_NOT_FOUND', 'الشركة غير موجودة.'); if (current >= maxUsers) throw new MemberFailure('MAX_USERS_REACHED', 'تم الوصول إلى الحد الأقصى للمستخدمين.'); const ts = admin.firestore.FieldValue.serverTimestamp(); tx.create(memberRef!, { uid, companyId: companyRef.id, name, email: isWorker ? null : email, role, status: 'active', phone: normalize(data.phone) || null, ...(workerRef ? { workerId: workerRef.id } : {}), createdAt: ts, createdBy: auth!.uid, updatedAt: ts }); if (workerRef && workerSecretRef) { tx.create(workerRef, { name, username, authUid: uid, status: 'active', phone: normalize(data.phone) || null, createdAt: ts, createdBy: auth!.uid, updatedAt: ts }); tx.create(workerSecretRef, { loginCodeHash: hashWorkerLoginCode(loginCode), loginCodeVersion: 1, createdAt: ts, updatedAt: ts }); } tx.update(companyRef, { memberCount: current + 1, activeMemberCount: Number(company.data()?.activeMemberCount ?? current) + 1, updatedAt: ts }); });
      await this.audit(companyRef.id, 'company_member_created', auth!.uid, uid, role, { workerId: workerRef?.id || null });
      return ok('تم إنشاء العضو بنجاح.', { uid, ...(workerRef ? { workerId: workerRef.id } : {}) });
    } catch (error) { const code = error instanceof MemberFailure ? error.code : workerRef ? 'WORKER_CREATION_FAILED' : 'MEMBER_CREATION_FAILED'; const rollback = await this.rollback(uid, [memberRef, workerRef, workerSecretRef].filter(Boolean) as FirebaseFirestore.DocumentReference[]); return rollback ? fail(code, error instanceof Error ? error.message : 'تعذر إنشاء العضو.') : fail('ROLLBACK_FAILED', 'فشلت العملية وتعذر إكمال التراجع الآمن.'); }
  }
  async update(input: unknown, auth: AuthContext): Promise<UpdateCompanyMemberResponse> { const context = await this.authorize(auth); if ('success' in context) return context; const data = (input || {}) as UpdateCompanyMemberRequest; const uid = normalize(data.uid); const fields: Record<string, unknown> = {}; if (typeof data.name === 'string' && normalize(data.name)) fields.name = normalize(data.name); if (typeof data.phone === 'string') fields.phone = normalize(data.phone) || null; if (data.displaySettings && typeof data.displaySettings === 'object' && !Array.isArray(data.displaySettings)) fields.displaySettings = data.displaySettings; if (!uid || !Object.keys(fields).length) return fail('INVALID_INPUT', 'لا توجد بيانات مسموح بتعديلها.'); const target = context.company.ref.collection('members').doc(uid); const snapshot = await target.get(); if (!snapshot.exists) return fail('MEMBER_NOT_FOUND', 'العضو غير موجود.'); if (snapshot.data()?.role === 'company_super_admin') return fail('CANNOT_MANAGE_COMPANY_ADMIN', 'لا يمكن تعديل مدير الشركة الأعلى.'); await target.update({ ...fields, updatedAt: admin.firestore.FieldValue.serverTimestamp() }); if (fields.name) await this.deps.auth.updateUser(uid, { displayName: String(fields.name) }); await this.audit(context.company.id, 'company_member_updated', auth!.uid, uid, String(snapshot.data()?.role), { fields: Object.keys(fields) }); return ok('تم تحديث بيانات العضو.'); }
  async changeRole(input: unknown, auth: AuthContext): Promise<ChangeCompanyMemberRoleResponse> { const context = await this.authorize(auth); if ('success' in context) return context; const data = (input || {}) as ChangeCompanyMemberRoleRequest; const uid = normalize(data.uid); if (!uid || !['manager', 'employee', 'worker'].includes(data.role)) return fail('ROLE_NOT_ALLOWED', 'الدور المطلوب غير مسموح.'); if (uid === auth!.uid) return fail('SELF_ROLE_CHANGE_FORBIDDEN', 'لا يمكنك تغيير دورك بنفسك.'); const target = context.company.ref.collection('members').doc(uid); const snapshot = await target.get(); if (!snapshot.exists) return fail('MEMBER_NOT_FOUND', 'العضو غير موجود.'); const oldRole = snapshot.data()?.role; if (oldRole === 'company_super_admin') return fail('CANNOT_MANAGE_COMPANY_ADMIN', 'لا يمكن إدارة مدير الشركة الأعلى.'); if ((oldRole === 'worker') !== (data.role === 'worker')) return fail('ROLE_NOT_ALLOWED', 'تغيير الدور بين عامل ودور إداري غير مدعوم بأمان في هذه المرحلة.'); const rate = await this.rateLimit(context.company.id, auth!.uid, 'role'); if (rate) return rate; await target.update({ role: data.role, updatedAt: admin.firestore.FieldValue.serverTimestamp() }); await this.audit(context.company.id, 'company_member_role_changed', auth!.uid, uid, data.role, { previousRole: oldRole }); return ok('تم تغيير دور العضو.'); }
  async disable(input: unknown, auth: AuthContext): Promise<DisableCompanyMemberResponse> { const context = await this.authorize(auth); if ('success' in context) return context; const uid = normalize((input as DisableCompanyMemberRequest)?.uid); if (!uid) return fail('INVALID_INPUT', 'معرف العضو غير صالح.'); if (uid === auth!.uid) return fail('SELF_DISABLE_FORBIDDEN', 'لا يمكنك تعطيل حسابك بنفسك.'); const target = context.company.ref.collection('members').doc(uid); const snapshot = await target.get(); if (!snapshot.exists) return fail('MEMBER_NOT_FOUND', 'العضو غير موجود.'); const role = snapshot.data()?.role; if (role === 'company_super_admin') { const admins = await context.company.ref.collection('members').where('role', '==', 'company_super_admin').where('status', '==', 'active').limit(2).get(); return admins.size <= 1 ? fail('LAST_COMPANY_ADMIN', 'لا يمكن تعطيل آخر مدير أعلى للشركة.') : fail('CANNOT_MANAGE_COMPANY_ADMIN', 'لا يمكن تعطيل مدير الشركة الأعلى.'); } const rate = await this.rateLimit(context.company.id, auth!.uid, 'disable'); if (rate) return rate; await this.deps.auth.updateUser(uid, { disabled: true }); await this.deps.db.runTransaction(async tx => { const company = await tx.get(context.company.ref); tx.update(target, { status: 'disabled', updatedAt: admin.firestore.FieldValue.serverTimestamp() }); tx.update(context.company.ref, { activeMemberCount: Math.max(0, Number(company.data()?.activeMemberCount || 1) - 1) }); }); await this.audit(context.company.id, 'company_member_disabled', auth!.uid, uid, role); return ok('تم تعطيل العضو.'); }
  async reactivate(input: unknown, auth: AuthContext): Promise<ReactivateCompanyMemberResponse> { const context = await this.authorize(auth); if ('success' in context) return context; const uid = normalize((input as ReactivateCompanyMemberRequest)?.uid); if (!uid) return fail('INVALID_INPUT', 'معرف العضو غير صالح.'); const target = context.company.ref.collection('members').doc(uid); const snapshot = await target.get(); if (!snapshot.exists) return fail('MEMBER_NOT_FOUND', 'العضو غير موجود.'); const rate = await this.rateLimit(context.company.id, auth!.uid, 'reactivate'); if (rate) return rate; await this.deps.auth.updateUser(uid, { disabled: false }); await this.deps.db.runTransaction(async tx => { tx.update(target, { status: 'active', updatedAt: admin.firestore.FieldValue.serverTimestamp() }); tx.update(context.company.ref, { activeMemberCount: Math.max(0, Number(context.company.data()?.activeMemberCount || 0) + 1) }); }); await this.audit(context.company.id, 'company_member_reactivated', auth!.uid, uid, String(snapshot.data()?.role)); return ok('تمت إعادة تفعيل العضو.'); }
  async passwordReset(input: unknown, auth: AuthContext): Promise<SendCompanyMemberPasswordResetResponse> { const context = await this.authorize(auth); if ('success' in context) return context; const uid = normalize((input as SendCompanyMemberPasswordResetRequest)?.uid); const member = uid ? await context.company.ref.collection('members').doc(uid).get() : null; if (!member?.exists) return fail('MEMBER_NOT_FOUND', 'العضو غير موجود.'); const data = member.data() as MemberDoc; if (data.role === 'worker' || !emailPattern.test(String(data.email || ''))) return fail('RESET_NOT_SUPPORTED', 'إعادة تعيين كلمة المرور غير مدعومة لهذا العضو.'); const link = await this.deps.auth.generatePasswordResetLink(String(data.email)); await this.audit(context.company.id, 'company_member_password_reset_sent', auth!.uid, uid, String(data.role)); return this.deps.emulator ? ok('تم إنشاء رابط إعادة التعيين للاختبار فقط.', { testResetLink: link }) : ok('تم إرسال طلب إعادة تعيين كلمة المرور.'); }
  async resetWorkerCode(input: unknown, auth: AuthContext): Promise<ResetWorkerLoginCodeResponse> { const context = await this.authorize(auth); if ('success' in context) return context; const data = (input || {}) as ResetWorkerLoginCodeRequest; const workerId = normalize(data.workerId); if (!workerId || !this.validCode(typeof data.loginCode === 'string' ? data.loginCode : '')) return fail('INVALID_INPUT', 'كود العامل يجب أن يحتوي على ستة أحرف على الأقل ورقم واحد.'); const worker = context.company.ref.collection('workers').doc(workerId); const snapshot = await worker.get(); if (!snapshot.exists) return fail('MEMBER_NOT_FOUND', 'العامل غير موجود.'); const rate = await this.rateLimit(context.company.id, auth!.uid, 'worker-code'); if (rate) return rate; await context.company.ref.collection('workerSecrets').doc(workerId).set({ loginCodeHash: hashWorkerLoginCode(data.loginCode), loginCodeVersion: admin.firestore.FieldValue.increment(1), updatedAt: admin.firestore.FieldValue.serverTimestamp() }, { merge: true }); await this.audit(context.company.id, 'worker_login_code_reset', auth!.uid, String(snapshot.data()?.authUid || ''), 'worker', { workerId }); return ok('تمت إعادة تعيين كود العامل.'); }
  private async rollback(uid: string | undefined, refs: FirebaseFirestore.DocumentReference[]): Promise<boolean> { try { if (refs.length) await this.deps.db.runTransaction(async tx => refs.forEach(ref => tx.delete(ref))); if (uid) await this.deps.auth.deleteUser(uid); return true; } catch { return false; } }
}
class MemberFailure extends Error { constructor(readonly code: CompanyMemberError, message: string) { super(message); } }
