import * as crypto from 'node:crypto';
import type { Auth } from 'firebase-admin/auth';
import { FieldValue } from 'firebase-admin/firestore';

const admin = { firestore: { FieldValue } };
import type { ChangeCompanyMemberRoleRequest, ChangeCompanyMemberRoleResponse, CompanyMemberError, CompanyMemberResponse, CompanyRole, CreateCompanyMemberRequest, CreateCompanyMemberResponse, DeleteCompanyMemberRequest, DeleteCompanyMemberResponse, DisableCompanyMemberRequest, DisableCompanyMemberResponse, ManagedRole, ReactivateCompanyMemberRequest, ReactivateCompanyMemberResponse, ResetWorkerLoginCodeRequest, ResetWorkerLoginCodeResponse, SendCompanyMemberPasswordResetRequest, SendCompanyMemberPasswordResetResponse, UpdateCompanyMemberRequest, UpdateCompanyMemberResponse, UpdateOwnCompanyProfileRequest, UpdateOwnCompanyProfileResponse } from './apiTypes.js';
export type * from './apiTypes.js';

type AuthContext = { uid: string } | undefined;
type MemberDoc = { uid: string; companyId?: string; name?: string; email?: string; role?: CompanyRole; status?: string; workerId?: string; phone?: string };
type Deps = { db: FirebaseFirestore.Firestore; auth: Auth; emulator?: boolean };
const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const workerName = /^[a-z0-9_-]{2,80}$/i;
const ok = <T = Record<string, never>>(message: string, data?: T): CompanyMemberResponse<T> => data === undefined ? { success: true, code: 'OK', message } : { success: true, code: 'OK', message, data };
const fail = (code: CompanyMemberError, message: string): CompanyMemberResponse => ({ success: false, code, message });
const normalize = (v: unknown) => typeof v === 'string' ? v.trim() : '';
const hasMemberWritePermission = (role: CompanyRole) => role === 'company_super_admin' || role === 'manager';
export const hashWorkerLoginCode = (loginCode: string): string => { const salt = crypto.randomBytes(16); const N = 16384, r = 8, p = 1; const value = crypto.scryptSync(loginCode, salt, 64, { N, r, p, maxmem: 128 * 1024 * 1024 }); return `scrypt$${N}$${r}$${p}$${salt.toString('base64')}$${value.toString('base64')}`; };
export const canManageCompanyMember = (actorRole: CompanyRole, targetRole: CompanyRole, _action: 'create' | 'update' | 'role' | 'disable' | 'delete'): boolean => ['company_super_admin', 'manager'].includes(actorRole) && targetRole === 'manager';

export class CompanyMemberService {
  constructor(private readonly deps: Deps) {}

  private async caller(auth: AuthContext): Promise<{ company: FirebaseFirestore.DocumentSnapshot; member: FirebaseFirestore.QueryDocumentSnapshot } | CompanyMemberResponse> {
    if (!auth?.uid) return fail('UNAUTHORIZED', 'يجب تسجيل الدخول أولاً.');
    const matches = await this.deps.db.collectionGroup('members').where('uid', '==', auth.uid).get();
    const active = matches.docs.filter(doc => doc.data().status === 'active');
    if (active.length !== 1) return fail('UNAUTHORIZED', 'عضوية الشركة غير صالحة أو غير مفعلة.');
    const member = active[0]; const companyRef = member.ref.parent.parent;
    if (!companyRef) return fail('UNAUTHORIZED', 'عضوية الشركة غير صالحة.');
    const company = await companyRef.get();
    if (!company.exists) return fail('COMPANY_NOT_FOUND', 'الشركة غير موجودة.');
    if (!['active', 'trial'].includes(String(company.data()?.status))) return fail('COMPANY_INACTIVE', 'حالة الشركة لا تسمح بإدارة الأعضاء.');
    return { company, member };
  }
  private async authorize(auth: AuthContext): Promise<{ company: FirebaseFirestore.DocumentSnapshot; member: FirebaseFirestore.QueryDocumentSnapshot } | CompanyMemberResponse> {
    const context = await this.caller(auth);
    if ('success' in context) return context;
    if (!hasMemberWritePermission(context.member.data().role as CompanyRole)) return fail('FORBIDDEN', 'ليس لديك صلاحية إدارة أعضاء الشركة.');
    return context;
  }
  private async rateLimit(companyId: string, actor: string, action: string): Promise<CompanyMemberResponse | null> {
    const ref = this.deps.db.doc(`companyMemberRateLimits/${crypto.createHash('sha256').update(`${companyId}\0${actor}\0${action}`).digest('hex')}`);
    const allowed = await this.deps.db.runTransaction(async tx => { const snapshot = await tx.get(ref); const data = snapshot.data() || {}; const now = Date.now(); const windowStartedAt = typeof data.windowStartedAt === 'number' ? data.windowStartedAt : now; const inWindow = now - windowStartedAt < 60_000; const count = inWindow ? Number(data.count || 0) : 0; if (count >= 10) return false; tx.set(ref, { count: count + 1, windowStartedAt: inWindow ? windowStartedAt : now, updatedAt: FieldValue.serverTimestamp() }, { merge: true }); return true; });
    return allowed ? null : fail('FORBIDDEN', 'تم تجاوز الحد المؤقت لهذه العملية. حاول لاحقاً.');
  }
  private async audit(companyId: string, action: string, performedBy: string, targetUid: string, targetRole?: string, metadata: Record<string, unknown> = {}): Promise<void> {
    await this.deps.db.collection(`companies/${companyId}/auditLogs`).add({ action, companyId, targetUid, targetRole: targetRole || null, performedBy, metadata, success: true, timestamp: admin.firestore.FieldValue.serverTimestamp() });
  }
  private validCode(code: string) { return code.length >= 6 && code.length <= 128 && /[0-9]/.test(code); }

  async create(input: unknown, auth: AuthContext): Promise<CreateCompanyMemberResponse> {
    const context = await this.authorize(auth); if ('success' in context) return context;
    const rate = await this.rateLimit(context.company.id, auth!.uid, 'create'); if (rate) return rate;
    const data = (input || {}) as CreateCompanyMemberRequest; const name = normalize(data.name); const role = data.role;
    if (!name || role !== 'manager') return fail('INVALID_INPUT', 'يسمح من إدارة المديرين بإنشاء مدير فقط.');
    const isWorker = false; const email = normalize(data.email).toLowerCase(); const temporaryPassword = typeof data.temporaryPassword === 'string' ? data.temporaryPassword : ''; const username = normalize(data.username).toLowerCase(); const loginCode = typeof data.loginCode === 'string' ? data.loginCode : '';
    if (!emailPattern.test(email) || temporaryPassword.length < 12 || username || loginCode) return fail('INVALID_INPUT', 'بيانات إنشاء المدير أو كلمة المرور المؤقتة غير صحيحة.');
    const companyRef = context.company.ref; const maxUsers = Number(context.company.data()?.maxUsers);
    if (!Number.isInteger(maxUsers) || maxUsers < 1) return fail('INVALID_INPUT', 'إعداد maxUsers للشركة غير صالح.');
    if (!isWorker) { try { if (await this.deps.auth.getUserByEmail(email)) return fail('EMAIL_EXISTS', 'البريد الإلكتروني مستخدم بالفعل.'); } catch (e) { if ((e as { code?: string }).code !== 'auth/user-not-found') return fail('AUTH_CREATION_FAILED', 'تعذر التحقق من البريد الإلكتروني.'); } }
    let uid: string | undefined; let workerRef: FirebaseFirestore.DocumentReference | undefined; let workerSecretRef: FirebaseFirestore.DocumentReference | undefined; let memberRef: FirebaseFirestore.DocumentReference | undefined;
    try {
      if (isWorker) { const matches = await companyRef.collection('workers').where('username', '==', username).limit(1).get(); if (!matches.empty) return fail('USERNAME_EXISTS', 'اسم المستخدم مستخدم داخل هذه الشركة.'); workerRef = companyRef.collection('workers').doc(); workerSecretRef = companyRef.collection('workerSecrets').doc(workerRef.id); uid = `worker_${companyRef.id}_${workerRef.id}`; try { await this.deps.auth.createUser({ uid, displayName: name }); } catch { return fail('AUTH_CREATION_FAILED', 'تعذر إنشاء حساب العامل.'); } }
      else { try { uid = (await this.deps.auth.createUser({ displayName: name, email, password: temporaryPassword, emailVerified: false })).uid; } catch (e) { return (e as { code?: string }).code === 'auth/email-already-exists' ? fail('EMAIL_EXISTS', 'البريد الإلكتروني مستخدم بالفعل.') : fail('AUTH_CREATION_FAILED', 'تعذر إنشاء حساب المستخدم.'); } }
      await this.deps.auth.setCustomUserClaims(uid, { companyId: companyRef.id, role: 'manager' });
      memberRef = companyRef.collection('members').doc(uid);
      await this.deps.db.runTransaction(async tx => { const company = await tx.get(companyRef); const current = Number(company.data()?.memberCount || 0); if (!company.exists) throw new MemberFailure('COMPANY_NOT_FOUND', 'الشركة غير موجودة.'); if (current >= maxUsers) throw new MemberFailure('MAX_USERS_REACHED', 'تم الوصول إلى الحد الأقصى للمستخدمين.'); const companyCode = String(company.data()?.companyCode || ''); if (!/^\d{6}$/.test(companyCode)) throw new MemberFailure('INVALID_INPUT', 'رمز الشركة الرقمي غير صالح.'); const ts = admin.firestore.FieldValue.serverTimestamp(); tx.create(memberRef!, { uid, companyId: companyRef.id, companyCode, name, email: isWorker ? null : email, role, status: 'active', phone: normalize(data.phone) || null, ...(workerRef ? { workerId: workerRef.id } : {}), createdAt: ts, createdBy: auth!.uid, updatedAt: ts }); if (workerRef && workerSecretRef) { tx.create(workerRef, { companyId: companyRef.id, companyCode, name, username, usernameNormalized: username, authUid: uid, status: 'active', phone: normalize(data.phone) || null, createdAt: ts, createdBy: auth!.uid, updatedAt: ts }); tx.create(workerSecretRef, { loginCodeHash: hashWorkerLoginCode(loginCode), loginCodeVersion: 1, createdAt: ts, updatedAt: ts }); } tx.update(companyRef, { memberCount: current + 1, activeMemberCount: Number(company.data()?.activeMemberCount ?? current) + 1, updatedAt: ts }); });
      await memberRef.update({ jobTitle: normalize(data.jobTitle) || null });
      await this.audit(companyRef.id, 'company_manager_created', auth!.uid, uid, role);
      return ok('تم إنشاء العضو بنجاح.', { uid, ...(workerRef ? { workerId: workerRef.id, companyCode: String(context.company.data()?.companyCode || '') } : {}) });
    } catch (error) { const code = error instanceof MemberFailure ? error.code : workerRef ? 'WORKER_CREATION_FAILED' : 'MEMBER_CREATION_FAILED'; const rollback = await this.rollback(uid, [memberRef, workerRef, workerSecretRef].filter(Boolean) as FirebaseFirestore.DocumentReference[]); return rollback ? fail(code, error instanceof Error ? error.message : 'تعذر إنشاء العضو.') : fail('ROLLBACK_FAILED', 'فشلت العملية وتعذر إكمال التراجع الآمن.'); }
  }
  async update(input: unknown, auth: AuthContext): Promise<UpdateCompanyMemberResponse> { const context = await this.authorize(auth); if ('success' in context) return context; const data = (input || {}) as UpdateCompanyMemberRequest; const uid = normalize(data.uid); const fields: Record<string, unknown> = {}; if (typeof data.name === 'string' && normalize(data.name)) fields.name = normalize(data.name); if (typeof data.phone === 'string') fields.phone = normalize(data.phone) || null; if (typeof data.jobTitle === 'string') fields.jobTitle = normalize(data.jobTitle) || null; if (data.displaySettings && typeof data.displaySettings === 'object' && !Array.isArray(data.displaySettings)) fields.displaySettings = data.displaySettings; if (!uid || !Object.keys(fields).length) return fail('INVALID_INPUT', 'لا توجد بيانات مسموح بتعديلها.'); const target = context.company.ref.collection('members').doc(uid); const snapshot = await target.get(); if (!snapshot.exists) return fail('MEMBER_NOT_FOUND', 'العضو غير موجود.'); if (snapshot.data()?.role === 'company_super_admin') return fail('CANNOT_MANAGE_COMPANY_ADMIN', 'لا يمكن تعديل صاحب الشركة.'); if (snapshot.data()?.role !== 'manager') return fail('ROLE_NOT_ALLOWED', 'يمكن تعديل المديرين فقط من هذه الشاشة.'); await target.update({ ...fields, updatedAt: admin.firestore.FieldValue.serverTimestamp() }); if (fields.name) await this.deps.auth.updateUser(uid, { displayName: String(fields.name) }); await this.audit(context.company.id, 'company_manager_updated', auth!.uid, uid, 'manager', { fields: Object.keys(fields) }); return ok('تم تحديث بيانات المدير.'); }
  async changeRole(input: unknown, auth: AuthContext): Promise<ChangeCompanyMemberRoleResponse> { const context = await this.authorize(auth); if ('success' in context) return context; const data = (input || {}) as ChangeCompanyMemberRoleRequest; const uid = normalize(data.uid); if (!uid || data.role !== 'manager') return fail('ROLE_NOT_ALLOWED', 'دور المدير ثابت من شاشة إدارة المديرين.'); if (uid === auth!.uid) return fail('SELF_ROLE_CHANGE_FORBIDDEN', 'لا يمكنك تغيير دورك بنفسك.'); const target = context.company.ref.collection('members').doc(uid); const snapshot = await target.get(); if (!snapshot.exists) return fail('MEMBER_NOT_FOUND', 'العضو غير موجود.'); const oldRole = snapshot.data()?.role; if (oldRole === 'company_super_admin') return fail('CANNOT_MANAGE_COMPANY_ADMIN', 'لا يمكن إدارة صاحب الشركة.'); if (oldRole !== 'manager') return fail('ROLE_NOT_ALLOWED', 'لا يمكن تحويل حساب آخر إلى مدير من هذا المسار.'); return ok('الدور مضبوط بالفعل كمدير.'); }
  async disable(input: unknown, auth: AuthContext): Promise<DisableCompanyMemberResponse> { const context = await this.authorize(auth); if ('success' in context) return context; const uid = normalize((input as DisableCompanyMemberRequest)?.uid); if (!uid) return fail('INVALID_INPUT', 'معرف العضو غير صالح.'); if (uid === auth!.uid) return fail('SELF_DISABLE_FORBIDDEN', 'لا يمكنك تعطيل حسابك بنفسك.'); const target = context.company.ref.collection('members').doc(uid); const snapshot = await target.get(); if (!snapshot.exists) return fail('MEMBER_NOT_FOUND', 'العضو غير موجود.'); const role = snapshot.data()?.role; if (role === 'company_super_admin') return fail('CANNOT_MANAGE_COMPANY_ADMIN', 'لا يمكن تعطيل صاحب الشركة.'); if (role !== 'manager') return fail('ROLE_NOT_ALLOWED', 'تعطيل هذا الحساب غير متاح من إدارة المديرين.'); const rate = await this.rateLimit(context.company.id, auth!.uid, 'disable'); if (rate) return rate; await this.deps.auth.updateUser(uid, { disabled: true }); await this.deps.db.runTransaction(async tx => { const company = await tx.get(context.company.ref); tx.update(target, { status: 'disabled', updatedAt: admin.firestore.FieldValue.serverTimestamp() }); tx.update(context.company.ref, { activeMemberCount: Math.max(0, Number(company.data()?.activeMemberCount || 1) - 1) }); }); await this.audit(context.company.id, 'company_manager_disabled', auth!.uid, uid, role); return ok('تم تعطيل المدير.'); }
  async reactivate(input: unknown, auth: AuthContext): Promise<ReactivateCompanyMemberResponse> { const context = await this.authorize(auth); if ('success' in context) return context; const uid = normalize((input as ReactivateCompanyMemberRequest)?.uid); if (!uid) return fail('INVALID_INPUT', 'معرف العضو غير صالح.'); const target = context.company.ref.collection('members').doc(uid); const snapshot = await target.get(); if (!snapshot.exists) return fail('MEMBER_NOT_FOUND', 'العضو غير موجود.'); if (snapshot.data()?.role === 'company_super_admin') return fail('CANNOT_MANAGE_COMPANY_ADMIN', 'لا يمكن تعديل حالة صاحب الشركة.'); if (snapshot.data()?.role !== 'manager') return fail('ROLE_NOT_ALLOWED', 'إعادة تفعيل هذا الحساب غير متاحة من إدارة المديرين.'); const rate = await this.rateLimit(context.company.id, auth!.uid, 'reactivate'); if (rate) return rate; await this.deps.auth.updateUser(uid, { disabled: false }); await this.deps.db.runTransaction(async tx => { tx.update(target, { status: 'active', updatedAt: admin.firestore.FieldValue.serverTimestamp() }); tx.update(context.company.ref, { activeMemberCount: Math.max(0, Number(context.company.data()?.activeMemberCount || 0) + 1) }); }); await this.audit(context.company.id, 'company_manager_reactivated', auth!.uid, uid, 'manager'); return ok('تمت إعادة تفعيل المدير.'); }
  async passwordReset(input: unknown, auth: AuthContext): Promise<SendCompanyMemberPasswordResetResponse> { const context = await this.authorize(auth); if ('success' in context) return context; const uid = normalize((input as SendCompanyMemberPasswordResetRequest)?.uid); const member = uid ? await context.company.ref.collection('members').doc(uid).get() : null; if (!member?.exists) return fail('MEMBER_NOT_FOUND', 'العضو غير موجود.'); const data = member.data() as MemberDoc; if (data.role === 'company_super_admin') return fail('CANNOT_MANAGE_COMPANY_ADMIN', 'لا يمكن إعادة تعيين كلمة مرور صاحب الشركة من إدارة المديرين.'); if (data.role !== 'manager' || !emailPattern.test(String(data.email || ''))) return fail('RESET_NOT_SUPPORTED', 'إعادة تعيين كلمة المرور غير مدعومة لهذا العضو.'); const link = await this.deps.auth.generatePasswordResetLink(String(data.email)); await this.audit(context.company.id, 'company_manager_password_reset_sent', auth!.uid, uid, String(data.role)); return this.deps.emulator ? ok('تم إنشاء رابط إعادة التعيين للاختبار فقط.', { testResetLink: link }) : ok('تم إرسال طلب إعادة تعيين كلمة المرور.'); }
  async deleteMember(input: unknown, auth: AuthContext): Promise<DeleteCompanyMemberResponse> { const context = await this.authorize(auth); if ('success' in context) return context; const uid = normalize((input as DeleteCompanyMemberRequest)?.uid); if (!uid || uid === auth!.uid) return fail('FORBIDDEN', 'لا يمكنك حذف حسابك الحالي.'); const target = context.company.ref.collection('members').doc(uid); const snapshot = await target.get(); if (!snapshot.exists) return fail('MEMBER_NOT_FOUND', 'المدير غير موجود.'); if (snapshot.data()?.role === 'company_super_admin') return fail('CANNOT_MANAGE_COMPANY_ADMIN', 'لا يمكن حذف صاحب الشركة.'); if (snapshot.data()?.role !== 'manager') return fail('ROLE_NOT_ALLOWED', 'الحذف من هذه الشاشة متاح للمديرين فقط.'); await this.deps.auth.deleteUser(uid); await this.deps.db.runTransaction(async tx => { const company = await tx.get(context.company.ref); tx.delete(target); tx.update(context.company.ref, { memberCount: Math.max(0, Number(company.data()?.memberCount || 1) - 1), activeMemberCount: Math.max(0, Number(company.data()?.activeMemberCount || 1) - (snapshot.data()?.status === 'active' ? 1 : 0)), updatedAt: admin.firestore.FieldValue.serverTimestamp() }); }); await this.audit(context.company.id, 'company_manager_deleted', auth!.uid, uid, 'manager'); return ok('تم حذف المدير.'); }
  async updateOwnProfile(input: unknown, auth: AuthContext): Promise<UpdateOwnCompanyProfileResponse> { const context = await this.caller(auth); if ('success' in context) return context; const actor = context.member.data() as MemberDoc; if (!['company_super_admin', 'manager'].includes(String(actor.role))) return fail('FORBIDDEN', 'الملف الشخصي الإداري غير متاح لهذا الحساب.'); const data = (input || {}) as UpdateOwnCompanyProfileRequest; const name = typeof data.name === 'string' ? normalize(data.name) : ''; const phone = typeof data.phone === 'string' ? normalize(data.phone) : ''; const newPassword = typeof data.newPassword === 'string' ? data.newPassword : ''; if (!name && !phone && !newPassword) return fail('INVALID_INPUT', 'لا توجد بيانات مسموح بتعديلها.'); if (newPassword && newPassword.length < 12) return fail('INVALID_INPUT', 'كلمة المرور الجديدة يجب أن تكون 12 حرفًا على الأقل.'); const fields: Record<string, unknown> = { updatedAt: admin.firestore.FieldValue.serverTimestamp() }; if (name) fields.name = name; if (typeof data.phone === 'string') fields.phone = phone || null; await context.member.ref.set(fields, { merge: true }); if (name || newPassword) await this.deps.auth.updateUser(auth!.uid, { ...(name ? { displayName: name } : {}), ...(newPassword ? { password: newPassword } : {}) }); await this.audit(context.company.id, 'company_admin_profile_updated', auth!.uid, auth!.uid, String(actor.role), { nameChanged: Boolean(name), phoneChanged: typeof data.phone === 'string', passwordChanged: Boolean(newPassword) }); return ok('تم تحديث الملف الشخصي.'); }
  async resetWorkerCode(input: unknown, auth: AuthContext): Promise<ResetWorkerLoginCodeResponse> { const context = await this.authorize(auth); if ('success' in context) return context; const data = (input || {}) as ResetWorkerLoginCodeRequest; const workerId = normalize(data.workerId); if (!workerId || !this.validCode(typeof data.loginCode === 'string' ? data.loginCode : '')) return fail('INVALID_INPUT', 'كود العامل يجب أن يحتوي على ستة أحرف على الأقل ورقم واحد.'); const worker = context.company.ref.collection('workers').doc(workerId); const snapshot = await worker.get(); if (!snapshot.exists) return fail('MEMBER_NOT_FOUND', 'العامل غير موجود.'); const rate = await this.rateLimit(context.company.id, auth!.uid, 'worker-code'); if (rate) return rate; await context.company.ref.collection('workerSecrets').doc(workerId).set({ loginCodeHash: hashWorkerLoginCode(data.loginCode), loginCodeVersion: admin.firestore.FieldValue.increment(1), updatedAt: admin.firestore.FieldValue.serverTimestamp() }, { merge: true }); await this.audit(context.company.id, 'worker_login_code_reset', auth!.uid, String(snapshot.data()?.authUid || ''), 'worker', { workerId }); return ok('تمت إعادة تعيين كود العامل.'); }
  private async rollback(uid: string | undefined, refs: FirebaseFirestore.DocumentReference[]): Promise<boolean> { try { if (refs.length) await this.deps.db.runTransaction(async tx => refs.forEach(ref => tx.delete(ref))); if (uid) await this.deps.auth.deleteUser(uid); return true; } catch { return false; } }
}
class MemberFailure extends Error { constructor(readonly code: CompanyMemberError, message: string) { super(message); } }
