import React, { useState } from 'react';
import { Calculator, Plus, Settings2, Trash2 } from 'lucide-react';
import { useData } from '../../context/DataContext';
import type { OrderPriceCatalogItem } from '../../types';

const newId = (prefix: string) => `${prefix}_${crypto.randomUUID?.() || `${Date.now()}_${Math.random().toString(36).slice(2)}`}`;

export const OrderCalculatorModule: React.FC<{ onOpenCalculator: () => void }> = ({ onOpenCalculator }) => {
  const { settings, updateSettings } = useData();
  const [catalog, setCatalog] = useState<OrderPriceCatalogItem[]>(settings.orderPriceCatalog || []);
  const [name, setName] = useState('');
  const [price, setPrice] = useState('');
  const [isSaving, setIsSaving] = useState(false);
  const saveCatalog = async (next: OrderPriceCatalogItem[]) => { setCatalog(next); setIsSaving(true); try { await updateSettings({ orderPriceCatalog: next }); } finally { setIsSaving(false); } };
  const addCatalogItem = async () => { const cleanName = name.trim(); const unitPrice = Number(price); if (!cleanName || !Number.isFinite(unitPrice) || unitPrice < 0) return; await saveCatalog([...catalog, { id: newId('price'), name: cleanName, unitPrice }]); setName(''); setPrice(''); };
  return <div dir="rtl" className="mx-auto max-w-5xl space-y-6 animate-in fade-in duration-300">
    <header className="flex flex-col items-start justify-between gap-4 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:flex-row sm:items-center"><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-emerald-100 text-emerald-700 dark:bg-emerald-950/50 dark:text-emerald-300"><Calculator className="h-6 w-6" /></div><div><h1 className="text-xl font-black text-slate-900 dark:text-white">حاسبة الأسعار</h1><p className="mt-0.5 text-xs text-slate-500">احسب عرض العميل مباشرة، بدون إنشاء أو تعديل أوردر.</p></div></div><button type="button" onClick={onOpenCalculator} className="flex items-center gap-2 rounded-xl bg-emerald-600 px-5 py-3 text-xs font-black text-white shadow-sm hover:bg-emerald-700"><Calculator className="h-4 w-4" />فتح الحاسبة</button></header>
    <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="mb-4 flex items-center gap-2"><Settings2 className="h-5 w-5 text-amber-500" /><div><h2 className="font-black text-slate-900 dark:text-white">إعدادات الحاسبة</h2><p className="text-xs text-slate-500">أضف الخدمات أو المكوّنات والسعر للوحدة. تُحفظ القائمة لاستخدامها في أي وقت.</p></div></div><div className="flex flex-col gap-2 sm:flex-row"><input value={name} onChange={(event) => setName(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') { event.preventDefault(); void addCatalogItem(); } }} placeholder="اسم المكوّن أو الخدمة" className="min-w-0 flex-1 rounded-xl border border-slate-200 bg-slate-50 px-3.5 py-2.5 text-sm font-semibold outline-none focus:ring-2 focus:ring-emerald-500 dark:border-slate-700 dark:bg-slate-800" /><input type="number" min="0" value={price} onChange={(event) => setPrice(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') { event.preventDefault(); void addCatalogItem(); } }} placeholder="سعر الوحدة" className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3.5 py-2.5 text-sm font-semibold outline-none focus:ring-2 focus:ring-emerald-500 dark:border-slate-700 dark:bg-slate-800 sm:w-40" /><button type="button" onClick={() => void addCatalogItem()} disabled={isSaving} className="flex items-center justify-center gap-1.5 rounded-xl bg-amber-500 px-4 py-2.5 text-xs font-black text-slate-950 hover:bg-amber-400 disabled:opacity-60"><Plus className="h-4 w-4" />إضافة</button></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{catalog.length ? catalog.map((item) => <div key={item.id} className="flex items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 p-3 dark:border-slate-700 dark:bg-slate-800"><span className="min-w-0 flex-1 truncate text-sm font-bold text-slate-800 dark:text-slate-100">{item.name}</span><strong className="font-mono text-sm text-emerald-700 dark:text-emerald-300">{item.unitPrice.toLocaleString()}</strong><button type="button" onClick={() => void saveCatalog(catalog.filter((entry) => entry.id !== item.id))} className="rounded-lg p-1 text-rose-500 hover:bg-rose-50 dark:hover:bg-rose-950/30" aria-label={`حذف ${item.name}`}><Trash2 className="h-4 w-4" /></button></div>) : <p className="col-span-full rounded-xl bg-slate-50 p-5 text-center text-sm text-slate-400 dark:bg-slate-800/60">أضف أول مكوّن لتبدأ الحاسبة.</p>}</div></section>
  </div>;
};
